### ISSUE TITLE
Can't import handlebars

### ISSUE THREAD

**Issue by kentico-ericd** [alosaur/handlebars#1]
`$ deno --version
deno 1.0.0-rc3
v8 8.4.300
typescript 3.8.3`

I'm trying to run a simple server using [deno-express](https://github.com/NMathar/deno-express/) and handlebars

```
import { Handlebars } from 'https://deno.land/x/handlebars/mod.ts'
import * as expressive from 'https://raw.githubusercontent.com/NMathar/deno-express/master/mod.ts';

(async () => {
  const port = 3000;
  const app = new expressive.App();
  const handle = new Handlebars();
  app.use(expressive.simpleLog());
  app.use(expressive.static_('./public'));
  app.use(expressive.bodyParser.json());

  app.get('/', async (req, res) => {
    res.body = await handle.renderView('index', { name: 'Alosaur' });
  });

  const server = await app.listen(port);
  console.log('app listening on port ' + server.port);
})();
```

But it won't run showing the below error. Running the file works fine as soon as the handlebars `import` is removed.

```
error: TS2339 [ERROR]: Property 'utime' does not exist on type 'typeof Deno'.
    await Deno.utime(dest, statInfo.atime, statInfo.mtime);
               ~~~~~
    at https://deno.land/std/fs/copy.ts:90:16

TS2339 [ERROR]: Property 'utimeSync' does not exist on type 'typeof Deno'.
    Deno.utimeSync(dest, statInfo.atime, statInfo.mtime);
         ~~~~~~~~~
    at https://deno.land/std/fs/copy.ts:101:10

TS2339 [ERROR]: Property 'symlink' does not exist on type 'typeof Deno'.
  await Deno.symlink(originSrcFilePath, dest, type);
             ~~~~~~~
    at https://deno.land/std/fs/copy.ts:114:14

TS2339 [ERROR]: Property 'utime' does not exist on type 'typeof Deno'.
    await Deno.utime(dest, statInfo.atime, statInfo.mtime);
               ~~~~~
    at https://deno.land/std/fs/copy.ts:119:16

TS2339 [ERROR]: Property 'symlinkSync' does not exist on type 'typeof Deno'.
  Deno.symlinkSync(originSrcFilePath, dest, type);
       ~~~~~~~~~~~
    at https://deno.land/std/fs/copy.ts:132:8

TS2339 [ERROR]: Property 'utimeSync' does not exist on type 'typeof Deno'.
    Deno.utimeSync(dest, statInfo.atime, statInfo.mtime);
         ~~~~~~~~~
    at https://deno.land/std/fs/copy.ts:137:10

TS2339 [ERROR]: Property 'utime' does not exist on type 'typeof Deno'.
    await Deno.utime(dest, srcStatInfo.atime, srcStatInfo.mtime);
               ~~~~~
    at https://deno.land/std/fs/copy.ts:157:16

TS2339 [ERROR]: Property 'utimeSync' does not exist on type 'typeof Deno'.
    Deno.utimeSync(dest, srcStatInfo.atime, srcStatInfo.mtime);
         ~~~~~~~~~
    at https://deno.land/std/fs/copy.ts:185:10

TS2339 [ERROR]: Property 'link' does not exist
on type 'typeof Deno'.
  await Deno.link(src, dest);
             ~~~~
    at https://deno.land/std/fs/ensure_link.ts:28:14

TS2339 [ERROR]: Property 'linkSync' does not exist on type 'typeof Deno'.
  Deno.linkSync(src, dest);
       ~~~~~~~~
    at https://deno.land/std/fs/ensure_link.ts:52:8

TS2339 [ERROR]: Property 'symlink' does not exist on type 'typeof Deno'.
  await Deno.symlink(src, dest, srcFilePathType);
             ~~~~~~~
    at https://deno.land/std/fs/ensure_symlink.ts:31:14

TS2339 [ERROR]: Property 'symlinkSync' does not exist on type 'typeof Deno'.
  Deno.symlinkSync(src, dest, srcFilePathType);       ~~~~~~~~~~~
    at https://deno.land/std/fs/ensure_symlink.ts:58:8
```

**Comment by irustm** [comment]
You must use the flag --unstable in Deno v1 `deno run --unstable'.
because Deno.std is not stable. 

https://github.com/denoland/deno/issues/5175
