### ISSUE TITLE
Can’t use on Deno Deploy

### ISSUE THREAD

**Issue by gustavocadev** [alosaur/handlebars#15]
```
[uncaught application error]: EvalError - Code generation from strings disallowed for this context

at JavaScriptCompiler.Function (<anonymous>)
    at JavaScriptCompiler.createFunctionContext (https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/compiler/javascript-compiler.dew.js:275:25)
    at JavaScriptCompiler.compile (https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/compiler/javascript-compiler.dew.js:146:21)
    at JavaScriptCompiler.compileChildren (https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/compiler/javascript-compiler.dew.js:819:51)
    at JavaScriptCompiler.compile (https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/compiler/javascript-compiler.dew.js:105:12)
    at compileInput (https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/compiler/compiler.dew.js:486:55)
    at ret (https://dev.jspm.io/npm:handlebars@4.7.6/dist/cjs/handlebars/compiler/compiler.dew.js:493:20)
    at Handlebars.render (https://deno.land/x/handlebars@v0.8.0/mod.ts:71:16)
    at async Handlebars.renderView (https://deno.land/x/handlebars@v0.8.0/mod.ts:53:22)
    at async renderIndex (file:///src/controllers/renderPages.controllers.ts:6:25)
```

**Comment by irustm** [comment]
Handlebars works with the `eval` function, I think `eval` is deliberately disabled in deno deploy

https://github.com/handlebars-lang/handlebars.js/blob/6790c080c641ef2b44e663800e1794fae180977a/spec/env/browser.js#L41
