### ISSUE TITLE
Doesn't import Handlebars

### ISSUE THREAD

**Issue by shawnthehumble** [alosaur/handlebars#3]
I'm using Deno 1.0.3 on MacOS 10.14.6
Run with the commands: deno run -A --unstable main.ts

I only typed:
import { Handlebars } from "https://deno.land/x/handlebars/mod.ts";

Not even written any code.  I get the following errors:

`error: TS2345 [ERROR]: Argument of type '"file" | "dir" | "symlink" | undefined' is not assignable to parameter of type 'SymlinkOptions | undefined'.
  Type '"file"' is not assignable to type 'SymlinkOptions | undefined'.
  await Deno.symlink(originSrcFilePath, dest, type);
                                              ~~~~
    at https://deno.land/std@0.51.0/fs/copy.ts:114:47
`

`TS2345 [ERROR]: Argument of type '"file" | "dir" | "symlink" | undefined' is not assignable to parameter of type 'SymlinkOptions | undefined'.
  Type '"file"' is not assignable to type 'SymlinkOptions | undefined'.
  Deno.symlinkSync(originSrcFilePath, dest, type);
                                            ~~~~
    at https://deno.land/std@0.51.0/fs/copy.ts:132:45
`

`TS2345 [ERROR]: Argument of type '"file" | "dir" | "symlink" | undefined' is not assignable to parameter of type 'SymlinkOptions | undefined'.
  Type '"file"' is not assignable to type 'SymlinkOptions | undefined'.
  await Deno.symlink(src, dest, srcFilePathType);
                                ~~~~~~~~~~~~~~~
    at https://deno.land/std@0.51.0/fs/ensure_symlink.ts:31:33
`

`TS2345 [ERROR]: Argument of type '"file" | "dir" | "symlink" | undefined' is not assignable to parameter of type 'SymlinkOptions | undefined'.
  Type '"file"' is not assignable to type 'SymlinkOptions | undefined'.
  Deno.symlinkSync(src, dest, srcFilePathType);
                              ~~~~~~~~~~~~~~~
    at https://deno.land/std@0.51.0/fs/ensure_symlink.ts:58:31
`

This is when I pull from master or "v0.2.2"

**Comment by shawnthehumble** [comment]
I was able to fix this by updating the std@0.54.0.  I checked a PR without updating the test and the PR build failed, but I also updated the test after and it works fine.
